version: '2'

services:
  frontend-test:
    build: ./frontend/
    command: npm run test:watch
    environment:
      - NODE_ENV=development
    volumes:
      - ./frontend:/usr/app
      - /usr/app/node_modules
    depends_on:
      - frontend
    tty: true
    restart: on-failure
